# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

LTO_ENABLE := yes
RGBLIGHT_ENABLE = no
OLED_ENABLE = no
AUDIO_ENABLE = no
ENCODER_ENABLE = no
TAP_DANCE_ENABLE = yes
CONSOLE_ENABLE= no

HAPTIC_ENABLE = yes
HAPTIC_DRIVER += DRV2605L
